import "./globals.css";
import Navbar from "../components/Navbar/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="py-8 px-10 bg-[#ECECEC]">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
